# -*- mode: ruby -*-
# vi: set ft=ruby :

# you're doing.
Vagrant.configure("2") do |config|

  # boxes at https://vagrantcloud.com/search.
  # 设置主机名称
  config.vm.hostname="cherry"
  # 设置使用那个box
  config.vm.box = "centos-docker"
  # 设置使用的版本
  config.vm.box_version="1.4"

  # docker compose配置
  config.vm.provision:docker
  config.vm.provision:docker_compose,
  yml:[
   "/cherry/docker-compose.yml"
  ],
  rebuild: true,
  run:"always"

  config.vm.network "forwarded_port", guest: 2375, host: 2375
  config.vm.network "forwarded_port", guest: 6379, host: 6379
  config.vm.network "forwarded_port", guest: 22, host: 2222
  config.vm.network "forwarded_port", guest: 8848, host: 8848
  config.vm.network "forwarded_port", guest: 3306, host: 3306
  config.vm.network "forwarded_port", guest: 8180, host: 8180
  config.vm.network "forwarded_port", guest: 9876, host: 9876

  # 同步目录
  config.vm.synced_folder ".", "/cherry",type: "virtualbox"
  # windows
  #config.vm.synced_folder ".", "/cherry", type: "rsync"
  #config.ssh.username = "vagrant"
  #config.ssh.password = "vagrant"

  #virtualbox
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"
    vb.cpus=2
    vb.name="cherry-server"
  end
end
