# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.hostname = "cherry"

  config.vm.box = "zhaoyunxing/docker"
  config.vm.box_version = "1.8"

  config.vm.network "private_network", ip: "192.168.56.200"

  config.vm.synced_folder ".", "/vagrant", type: "rsync"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "3072"
    vb.name="cherry"
    vb.cpus=2
  end
end
